module.exports = {
  USER_ROLES: {
    CUSTOMER: "CUSTOMER",
    STAFF: "STAFF",
    MANAGER: "MANAGER",
    ADMIN: "ADMIN",
    ALL: ["CUSTOMER", "STAFF", "MANAGER", "ADMIN"],
  },
  ORDER_STATUS: {
    // CONSTANTS OF STATUS CARTS AND ORDERS
    PENDING: "PENDING",
    DELIVERED: "DELIVERED",
    CANCELLED : "CANCELLED",
    DONE: "DONE",
    REFUNDED: "REFUNDED",
  }
};
